projects:
  aws-lambda-dynamo:
    schemaPath: src/graphql/schema.json
    includes:
      - QueMutSubs
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: .
        region: us-east-1
        apiId: qzvdwpzy2jgztlkkkyxp3m3sp4
        maxDepth: 2
extensions:
  amplify:
    version: 3
